# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventBusExample' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for EventBusExample
    pod 'AsyncEventBus', :path=>'../'


  target 'EventBusExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
